
require tppg2.inc

WKS_DTB = "sp7021-ltpp3g2-empty.dtb"

UBOOT_CONFIG:append = " a7021_dsxe"
UBOOT_CONFIG[a7021_dsxe] = "sp7021_dsxe_defconfig"

KERNEL_DEVICETREE += "sp7021-dsx.dtb"
KERNEL_DEVICETREE += "sp7021-ltpp3g2revF.dtb"

ISP_PROGRESS = "tps"
ISP_VERIFY = "1"

BB_CHECK_SSL_CERTS = "0"
