SCONF_VERSION = "1"

SDKMACHINE ?= "x86_64"

DL_DIR ?= "${HOME}/archives/oe_sources/"
SSTATE_DIR ?= "/disk2/build.tibbo.${LAYERSERIES_CORENAMES}.0/sstate-cache"
TMPDIR = "/disk2/build.tibbo.${LAYERSERIES_CORENAMES}.0/tmp"

BB_DISKMON_DIRS ?= ""

PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
PACKAGECONFIG:append:pn-nativesdk-qemu = " sdl"

require site.${LAYERSERIES_CORENAMES}.inc

OECORENOTESCONF="${TOPDIR}/meta-tibbo/conf/conf-notes.txt"
