DISTRO = "tin"

require distro.gen.inc

DISTRO_NAME:append = " - tiny"

DISTRO_FEATURES:append = " largefile ptest multiarch"
#DISTRO_FEATURES:append = " ext2 ipv4 ipv6 usbgadget usbhost vfat ldconfig"
