DISTRO = "tps"

require distro.gen.inc

DISTRO_NAME:append = ""

DISTRO_FEATURES:append = " largefile opengl ptest multiarch x11 wayland"
DISTRO_FEATURES:append = " bluetooth wifi 3g"
DISTRO_FEATURES:append = " pam"
# for optional meta-security layer: fscrypt
DISTRO_FEATURES:append = " security"

# set systemd as default init manager
require conf/distro/include/init-manager-systemd.inc
VIRTUAL-RUNTIME_init_manager = "systemd"
# set systemd as default init manager /
