#!/bin/sh
# Copyright (C) 2011 O.S. Systems Software LTDA.
# Licensed on MIT

rootfs_enabled() {
	return 0
}

rootfs_run() {
        if [ -z "$ROOTFS_DIR" ]; then
		return
        fi
	C=0
	delay=${bootparam_rootdelay:-1}
	timeout=${bootparam_roottimeout:-5}
	while ! mountpoint -q $ROOTFS_DIR; do
		if [ $(( $C * $delay )) -gt $timeout ]; then
			fatal "root '$bootparam_root' doesn't exist or does not contain a /dev."
		fi

		if [ -n "$bootparam_root" ]; then
			debug "No e2fs compatible filesystem has been mounted, mounting $bootparam_root..."

			if [ "`echo ${bootparam_root} | cut -c1-5`" = "UUID=" ]; then
				root_uuid=`echo $bootparam_root | cut -c6-`
				bootparam_root="/dev/disk/by-uuid/$root_uuid"
			elif [ "`echo ${bootparam_root} | cut -c1-9`" = "PARTUUID=" ]; then
				root_partuuid=`echo $bootparam_root | cut -c10-`
				bootparam_root="/dev/disk/by-partuuid/$root_partuuid"
			elif [ "`echo ${bootparam_root} | cut -c1-10`" = "PARTLABEL=" ]; then
				root_partlabel=`echo $bootparam_root | cut -c11-`
				bootparam_root="/dev/disk/by-partlabel/$root_partlabel"
			elif [ "`echo ${bootparam_root} | cut -c1-6`" = "LABEL=" ]; then
				root_label=`echo $bootparam_root | cut -c7-`
				bootparam_root="/dev/disk/by-label/$root_label"
			fi

			if [ -e "$bootparam_root" ]; then
				flags=""
				if [ -n "$bootparam_ro" ] && ! echo "$bootparam_rootflags" | grep -w -q "ro"; then
					if [  -n "$bootparam_rootflags" ]; then
						bootparam_rootflags="$bootparam_rootflags,"
					fi
					bootparam_rootflags="${bootparam_rootflags}ro"
				fi
				if [ -n "$bootparam_rootflags" ]; then
					flags="$flags -o$bootparam_rootflags"
				fi
				if [ -n "$bootparam_rootfstype" ]; then
					flags="$flags -t$bootparam_rootfstype"
				fi
				mount $flags $bootparam_root $ROOTFS_DIR
				x=$?
				if mountpoint -q $ROOTFS_DIR; then
					break
				else
					# It is unlikely to change, but keep trying anyway.
					# Perhaps we pick a different device next time.
					umount $ROOTFS_DIR
				fi
				# if mount was not successfull
				if [ 0 -ne $x ]; then
					msg "$bootparam_root mount attempt #$C was not successfull"
					# find the FS type
					ft="$bootparam_rootfstype"
					if [ ! -n "${ft}" ]; then
						x=`blkid $bootparam_root`
						debug "BLKID is $x"
						ft=`echo $x | sed -e 's/.*TYPE=\"\(.*\)\"/\1/g'`
					fi;
					msg "FS type is $ft"
					case "${ft}" in 
						*ext*)
							msg "Trying to repair with e2fsck"
							e2fsck -y $bootparam_root
							y=$?
							if [ 0 -ne $y ]; then
								msg "Seems the e2fsck run non-successfully"
								msg "Try to boot with init_fatal_sh=true"
							#	bootparam_init_fatal_sh="true"
							#	fatal "Going to rescue mode..."
							fi;
						;;
						"")
							msg "Assuming ext* for e2fssck..."
							e2fsck -y $bootparam_root
							y=$?
							if [ 0 -ne $y ]; then
								msg "Seems the e2fsck run non-successfully"
								msg "Try to boot with init_fatal_sh=true"
							#	bootparam_init_fatal_sh="true"
							#	fatal "Going to rescue mode..."
							fi;
						;;
						*ubi*)
						;;
						*)
							msg "Unknown FS type. Try to boot with init_fatal_sh=true"
						;;
					esac
				fi;
				# if mount was not successfull /
			fi
		fi
		debug "Sleeping for $delay second(s) to wait root to settle..."
		sleep $delay
		C=$(( $C + 1 ))
	done
}
